owner: streamsystem
repo: upstream

sites:
  - name: ssadmin
    url: https://ssadmin.streamsystem.com
  - name: Stream
    url: https://stream.dz
  - name: Bomare Company
    url: https://bomarecompany.com
  # - name: Assets
  #   url: https://assets.stream.dz

workflowSchedule:
  uptime: "3-58/10 * * * *"

status-website:
  # cname: upstream.streamsystem.com
  baseUrl: /upstream
  logoUrl: https://ssadmin.streamsystem.com/favicon.svg
  name: Upstream
  introTitle: "**Upstream**"
  introMessage: "Upstream uses Upptime, which is the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
